import { Pangolin } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const inter = Pangolin({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Kedy Generator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="retro">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
